name: stock_app
description: "A Flutter app to manage computer store stock."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # iOS style icons
  cupertino_icons: ^1.0.8

  # Firebase Core
  firebase_core: ^2.24.0

  # Cloud Firestore
  cloud_firestore: ^4.15.0

  # Firebase Storage (pour les images)
  firebase_storage: ^11.6.5

  # Image Picker pour sélectionner des photos depuis le téléphone
  image_picker: ^1.1.1

  # Provider pour la gestion d'état
  
  
  # Package pour le formatage des dates et nombres
  intl: ^0.19.0

  # PACKAGES POUR DESIGN ULTRA MODERNE (sans doublons)
  animations: ^2.0.11
  flutter_staggered_animations: ^1.1.0
  shimmer: ^3.0.0
  lottie: ^3.1.2
  google_fonts: ^6.2.1
  glassmorphism: ^3.0.0
  simple_animations: ^5.0.2
  flutter_animate: ^4.5.0
  motion: ^2.0.0
  shared_preferences: ^2.2.2
  provider: ^6.1.2
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/lakriraastock.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color: "#5E35B1"
  adaptive_icon_background: "#5E35B1"
  adaptive_icon_foreground: "assets/images/lakriraastock.png"